# /{application}/{profile}[/{label}]
# /{application}-{profile}.yml
# /{label}/{application}-{profile}.yml
# /{application}-{profile}.properties
# /{label}/{application}-{profile}.properties

GET http://localhost:8888/main/application-default.yml

###
GET http://localhost:9999/magic

###

GET http://localhost:8080/api/exercise/magic